# Generated by Django 5.2.3 on 2025-07-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='acervo.contato', verbose_name='contato'),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='emprestimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucao', to='acervo.emprestimo', verbose_name='Emprestimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensEmprestados', to='acervo.contato', verbose_name='contato'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='acervo.item', verbose_name='item emprestado'),
        ),
    ]
