# Generated by Django 5.2.3 on 2025-08-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_rename_nome_item_titulo_alter_devolucao_contato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='acervo/fotos'),
        ),
    ]
